//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int Id { get; set; }
        public string NAME { get; set; }
        public bool IS_FILE_LOG { get; set; }
        public string CUS { get; set; }
    }
}
