//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class HondaLock
    {
        public int ID { get; set; }
        public string ProductionID { get; set; }
        public string BoxID { get; set; }
        public string BoardNo { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Status { get; set; }
        public string Updator_Code { get; set; }
        public string Updator_Name { get; set; }
        public string Line { get; set; }
        public string NamePC { get; set; }
        public string ShiftDate { get; set; }
        public Nullable<bool> Repair { get; set; }
        public string Station { get; set; }
        public string Wo_Sap { get; set; }
        public string Wo_Mes { get; set; }
    }
}
