//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE_TIMELINE
    {
        public int Id { get; set; }
        public Nullable<int> IdTimeLine { get; set; }
        public Nullable<int> TimeIndex { get; set; }
        public string TimeFrom { get; set; }
        public string TimeTo { get; set; }
    }
}
