//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE_PASSRATE
    {
        public string ProductionID { get; set; }
        public string Line { get; set; }
        public string Time { get; set; }
        public Nullable<int> ProductPlan { get; set; }
        public Nullable<int> Actual { get; set; }
        public Nullable<int> IDCount { get; set; }
        public Nullable<int> IDCountBox { get; set; }
        public string BoxCurrent { get; set; }
        public Nullable<double> TimeCycleActual { get; set; }
        public int Id { get; set; }
        public string TimeValue { get; set; }
        public string NamePC { get; set; }
    }
}
