//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class LINE_MODEL
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public int PersonPerLine { get; set; }
        public double CycleTime { get; set; }
        public double WarnQuantity { get; set; }
        public double MinQuantity { get; set; }
        public string CharModel { get; set; }
        public Nullable<int> UseBarcode { get; set; }
        public Nullable<int> NumberInModel { get; set; }
        public Nullable<int> PCB { get; set; }
        public string Customer { get; set; }
        public Nullable<int> ContentLength { get; set; }
        public Nullable<int> ContentIndex { get; set; }
        public Nullable<bool> CheckFirst { get; set; }
        public string HistoryNo { get; set; }
    }
}
