//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATE_HISTORY
    {
        public int Id { get; set; }
        public string Line { get; set; }
        public string Model { get; set; }
        public string HostName { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string State { get; set; }
    }
}
