//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production.LineProductWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Line_Production.LineProductWebServiceReference.tbl_Product_RealtimeEntity))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tbl_Product_RealtimeEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class tbl_Product_RealtimeEntity : Line_Production.LineProductWebServiceReference.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LINE_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CUSTOMERField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MODELField;
        
        private System.Nullable<int> QTY_PLANField;
        
        private System.Nullable<int> QTY_ACTUALField;
        
        private System.Nullable<int> PEOPLEField;
        
        private System.Nullable<decimal> CYRCLETIME_PLANField;
        
        private System.Nullable<decimal> CYRCLETIME_ACTUALField;
        
        private System.Nullable<System.DateTime> UPDATE_TIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        private System.Nullable<int> DIFFField;
        
        private System.Nullable<int> ALARMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOTEField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string LINE_NO {
            get {
                return this.LINE_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.LINE_NOField, value) != true)) {
                    this.LINE_NOField = value;
                    this.RaisePropertyChanged("LINE_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CUSTOMER {
            get {
                return this.CUSTOMERField;
            }
            set {
                if ((object.ReferenceEquals(this.CUSTOMERField, value) != true)) {
                    this.CUSTOMERField = value;
                    this.RaisePropertyChanged("CUSTOMER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MODEL {
            get {
                return this.MODELField;
            }
            set {
                if ((object.ReferenceEquals(this.MODELField, value) != true)) {
                    this.MODELField = value;
                    this.RaisePropertyChanged("MODEL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> QTY_PLAN {
            get {
                return this.QTY_PLANField;
            }
            set {
                if ((this.QTY_PLANField.Equals(value) != true)) {
                    this.QTY_PLANField = value;
                    this.RaisePropertyChanged("QTY_PLAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> QTY_ACTUAL {
            get {
                return this.QTY_ACTUALField;
            }
            set {
                if ((this.QTY_ACTUALField.Equals(value) != true)) {
                    this.QTY_ACTUALField = value;
                    this.RaisePropertyChanged("QTY_ACTUAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> PEOPLE {
            get {
                return this.PEOPLEField;
            }
            set {
                if ((this.PEOPLEField.Equals(value) != true)) {
                    this.PEOPLEField = value;
                    this.RaisePropertyChanged("PEOPLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> CYRCLETIME_PLAN {
            get {
                return this.CYRCLETIME_PLANField;
            }
            set {
                if ((this.CYRCLETIME_PLANField.Equals(value) != true)) {
                    this.CYRCLETIME_PLANField = value;
                    this.RaisePropertyChanged("CYRCLETIME_PLAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> CYRCLETIME_ACTUAL {
            get {
                return this.CYRCLETIME_ACTUALField;
            }
            set {
                if ((this.CYRCLETIME_ACTUALField.Equals(value) != true)) {
                    this.CYRCLETIME_ACTUALField = value;
                    this.RaisePropertyChanged("CYRCLETIME_ACTUAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> UPDATE_TIME {
            get {
                return this.UPDATE_TIMEField;
            }
            set {
                if ((this.UPDATE_TIMEField.Equals(value) != true)) {
                    this.UPDATE_TIMEField = value;
                    this.RaisePropertyChanged("UPDATE_TIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.Nullable<int> DIFF {
            get {
                return this.DIFFField;
            }
            set {
                if ((this.DIFFField.Equals(value) != true)) {
                    this.DIFFField = value;
                    this.RaisePropertyChanged("DIFF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public System.Nullable<int> ALARM {
            get {
                return this.ALARMField;
            }
            set {
                if ((this.ALARMField.Equals(value) != true)) {
                    this.ALARMField = value;
                    this.RaisePropertyChanged("ALARM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string NOTE {
            get {
                return this.NOTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOTEField, value) != true)) {
                    this.NOTEField = value;
                    this.RaisePropertyChanged("NOTE");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LineProductWebServiceReference.LineProductRealtimeWebServiceSoap")]
    public interface LineProductRealtimeWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name entity from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRealtime", ReplyAction="*")]
        Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse UpdateRealtime(Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRealtime", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse> UpdateRealtimeAsync(Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest request);
        
        // CODEGEN: Generating message contract since element name customerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportData", ReplyAction="*")]
        Line_Production.LineProductWebServiceReference.ExportDataResponse ExportData(Line_Production.LineProductWebServiceReference.ExportDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExportData", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.ExportDataResponse> ExportDataAsync(Line_Production.LineProductWebServiceReference.ExportDataRequest request);
        
        // CODEGEN: Generating message contract since element name customerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetModels", ReplyAction="*")]
        Line_Production.LineProductWebServiceReference.GetModelsResponse GetModels(Line_Production.LineProductWebServiceReference.GetModelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetModels", ReplyAction="*")]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.GetModelsResponse> GetModelsAsync(Line_Production.LineProductWebServiceReference.GetModelsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRealtimeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRealtime", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.UpdateRealtimeRequestBody Body;
        
        public UpdateRealtimeRequest() {
        }
        
        public UpdateRealtimeRequest(Line_Production.LineProductWebServiceReference.UpdateRealtimeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRealtimeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Production.LineProductWebServiceReference.tbl_Product_RealtimeEntity entity;
        
        public UpdateRealtimeRequestBody() {
        }
        
        public UpdateRealtimeRequestBody(Line_Production.LineProductWebServiceReference.tbl_Product_RealtimeEntity entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRealtimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateRealtimeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.UpdateRealtimeResponseBody Body;
        
        public UpdateRealtimeResponse() {
        }
        
        public UpdateRealtimeResponse(Line_Production.LineProductWebServiceReference.UpdateRealtimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateRealtimeResponseBody {
        
        public UpdateRealtimeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportData", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.ExportDataRequestBody Body;
        
        public ExportDataRequest() {
        }
        
        public ExportDataRequest(Line_Production.LineProductWebServiceReference.ExportDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExportDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerID;
        
        public ExportDataRequestBody() {
        }
        
        public ExportDataRequestBody(string customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExportDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.ExportDataResponseBody Body;
        
        public ExportDataResponse() {
        }
        
        public ExportDataResponse(Line_Production.LineProductWebServiceReference.ExportDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ExportDataResponseBody {
        
        public ExportDataResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModels", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.GetModelsRequestBody Body;
        
        public GetModelsRequest() {
        }
        
        public GetModelsRequest(Line_Production.LineProductWebServiceReference.GetModelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetModelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string customerID;
        
        public GetModelsRequestBody() {
        }
        
        public GetModelsRequestBody(string customerID) {
            this.customerID = customerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetModelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetModelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.LineProductWebServiceReference.GetModelsResponseBody Body;
        
        public GetModelsResponse() {
        }
        
        public GetModelsResponse(Line_Production.LineProductWebServiceReference.GetModelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetModelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Production.LineProductWebServiceReference.ArrayOfString GetModelsResult;
        
        public GetModelsResponseBody() {
        }
        
        public GetModelsResponseBody(Line_Production.LineProductWebServiceReference.ArrayOfString GetModelsResult) {
            this.GetModelsResult = GetModelsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LineProductRealtimeWebServiceSoapChannel : Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LineProductRealtimeWebServiceSoapClient : System.ServiceModel.ClientBase<Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap>, Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap {
        
        public LineProductRealtimeWebServiceSoapClient() {
        }
        
        public LineProductRealtimeWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LineProductRealtimeWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineProductRealtimeWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LineProductRealtimeWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.UpdateRealtime(Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest request) {
            return base.Channel.UpdateRealtime(request);
        }
        
        public void UpdateRealtime(Line_Production.LineProductWebServiceReference.tbl_Product_RealtimeEntity entity) {
            Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest inValue = new Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.UpdateRealtimeRequestBody();
            inValue.Body.entity = entity;
            Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse retVal = ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).UpdateRealtime(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse> Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.UpdateRealtimeAsync(Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest request) {
            return base.Channel.UpdateRealtimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.UpdateRealtimeResponse> UpdateRealtimeAsync(Line_Production.LineProductWebServiceReference.tbl_Product_RealtimeEntity entity) {
            Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest inValue = new Line_Production.LineProductWebServiceReference.UpdateRealtimeRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.UpdateRealtimeRequestBody();
            inValue.Body.entity = entity;
            return ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).UpdateRealtimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.LineProductWebServiceReference.ExportDataResponse Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.ExportData(Line_Production.LineProductWebServiceReference.ExportDataRequest request) {
            return base.Channel.ExportData(request);
        }
        
        public void ExportData(string customerID) {
            Line_Production.LineProductWebServiceReference.ExportDataRequest inValue = new Line_Production.LineProductWebServiceReference.ExportDataRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.ExportDataRequestBody();
            inValue.Body.customerID = customerID;
            Line_Production.LineProductWebServiceReference.ExportDataResponse retVal = ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).ExportData(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.ExportDataResponse> Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.ExportDataAsync(Line_Production.LineProductWebServiceReference.ExportDataRequest request) {
            return base.Channel.ExportDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.ExportDataResponse> ExportDataAsync(string customerID) {
            Line_Production.LineProductWebServiceReference.ExportDataRequest inValue = new Line_Production.LineProductWebServiceReference.ExportDataRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.ExportDataRequestBody();
            inValue.Body.customerID = customerID;
            return ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).ExportDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.LineProductWebServiceReference.GetModelsResponse Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.GetModels(Line_Production.LineProductWebServiceReference.GetModelsRequest request) {
            return base.Channel.GetModels(request);
        }
        
        public Line_Production.LineProductWebServiceReference.ArrayOfString GetModels(string customerID) {
            Line_Production.LineProductWebServiceReference.GetModelsRequest inValue = new Line_Production.LineProductWebServiceReference.GetModelsRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.GetModelsRequestBody();
            inValue.Body.customerID = customerID;
            Line_Production.LineProductWebServiceReference.GetModelsResponse retVal = ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).GetModels(inValue);
            return retVal.Body.GetModelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.GetModelsResponse> Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap.GetModelsAsync(Line_Production.LineProductWebServiceReference.GetModelsRequest request) {
            return base.Channel.GetModelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Line_Production.LineProductWebServiceReference.GetModelsResponse> GetModelsAsync(string customerID) {
            Line_Production.LineProductWebServiceReference.GetModelsRequest inValue = new Line_Production.LineProductWebServiceReference.GetModelsRequest();
            inValue.Body = new Line_Production.LineProductWebServiceReference.GetModelsRequestBody();
            inValue.Body.customerID = customerID;
            return ((Line_Production.LineProductWebServiceReference.LineProductRealtimeWebServiceSoap)(this)).GetModelsAsync(inValue);
        }
    }
}
