//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Line_Production.USAPReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Line_Production.USAPReference.BCLBFLMEntity))]
    public partial class BaseEntity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BCLBFLMEntity", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BCLBFLMEntity : Line_Production.USAPReference.BaseEntity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_TYPEField;
        
        private System.Nullable<System.DateTime> REQ_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TN_NOField;
        
        private System.Nullable<int> TN_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PART_NOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MPN_NOField;
        
        private System.Nullable<decimal> REQ_QTYField;
        
        private System.Nullable<decimal> OS_QTYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PO_NOField;
        
        private System.Nullable<int> PO_LINEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_CODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_BRCDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DATE_CODEField;
        
        private System.Nullable<int> PRN_COUNTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BC_SITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WH_CODEField;
        
        private System.Nullable<System.DateTime> ISS_DATEField;
        
        private System.Nullable<System.DateTime> RQC_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UPD_USERField;
        
        private System.Nullable<System.DateTime> UPD_DATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WH_LOCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VEN_LTNOField;
        
        private System.Nullable<System.DateTime> MAKE_DATEField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BC_NO {
            get {
                return this.BC_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_NOField, value) != true)) {
                    this.BC_NOField = value;
                    this.RaisePropertyChanged("BC_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BC_TYPE {
            get {
                return this.BC_TYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_TYPEField, value) != true)) {
                    this.BC_TYPEField = value;
                    this.RaisePropertyChanged("BC_TYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> REQ_DATE {
            get {
                return this.REQ_DATEField;
            }
            set {
                if ((this.REQ_DATEField.Equals(value) != true)) {
                    this.REQ_DATEField = value;
                    this.RaisePropertyChanged("REQ_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TN_NO {
            get {
                return this.TN_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.TN_NOField, value) != true)) {
                    this.TN_NOField = value;
                    this.RaisePropertyChanged("TN_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> TN_LINE {
            get {
                return this.TN_LINEField;
            }
            set {
                if ((this.TN_LINEField.Equals(value) != true)) {
                    this.TN_LINEField = value;
                    this.RaisePropertyChanged("TN_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PART_NO {
            get {
                return this.PART_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PART_NOField, value) != true)) {
                    this.PART_NOField = value;
                    this.RaisePropertyChanged("PART_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string MPN_NO {
            get {
                return this.MPN_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.MPN_NOField, value) != true)) {
                    this.MPN_NOField = value;
                    this.RaisePropertyChanged("MPN_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> REQ_QTY {
            get {
                return this.REQ_QTYField;
            }
            set {
                if ((this.REQ_QTYField.Equals(value) != true)) {
                    this.REQ_QTYField = value;
                    this.RaisePropertyChanged("REQ_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> OS_QTY {
            get {
                return this.OS_QTYField;
            }
            set {
                if ((this.OS_QTYField.Equals(value) != true)) {
                    this.OS_QTYField = value;
                    this.RaisePropertyChanged("OS_QTY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string PO_NO {
            get {
                return this.PO_NOField;
            }
            set {
                if ((object.ReferenceEquals(this.PO_NOField, value) != true)) {
                    this.PO_NOField = value;
                    this.RaisePropertyChanged("PO_NO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<int> PO_LINE {
            get {
                return this.PO_LINEField;
            }
            set {
                if ((this.PO_LINEField.Equals(value) != true)) {
                    this.PO_LINEField = value;
                    this.RaisePropertyChanged("PO_LINE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string VEN_CODE {
            get {
                return this.VEN_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_CODEField, value) != true)) {
                    this.VEN_CODEField = value;
                    this.RaisePropertyChanged("VEN_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string VEN_BRCD {
            get {
                return this.VEN_BRCDField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_BRCDField, value) != true)) {
                    this.VEN_BRCDField = value;
                    this.RaisePropertyChanged("VEN_BRCD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DATE_CODE {
            get {
                return this.DATE_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.DATE_CODEField, value) != true)) {
                    this.DATE_CODEField = value;
                    this.RaisePropertyChanged("DATE_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public System.Nullable<int> PRN_COUNT {
            get {
                return this.PRN_COUNTField;
            }
            set {
                if ((this.PRN_COUNTField.Equals(value) != true)) {
                    this.PRN_COUNTField = value;
                    this.RaisePropertyChanged("PRN_COUNT");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string BC_SITE {
            get {
                return this.BC_SITEField;
            }
            set {
                if ((object.ReferenceEquals(this.BC_SITEField, value) != true)) {
                    this.BC_SITEField = value;
                    this.RaisePropertyChanged("BC_SITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string WH_CODE {
            get {
                return this.WH_CODEField;
            }
            set {
                if ((object.ReferenceEquals(this.WH_CODEField, value) != true)) {
                    this.WH_CODEField = value;
                    this.RaisePropertyChanged("WH_CODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=17)]
        public System.Nullable<System.DateTime> ISS_DATE {
            get {
                return this.ISS_DATEField;
            }
            set {
                if ((this.ISS_DATEField.Equals(value) != true)) {
                    this.ISS_DATEField = value;
                    this.RaisePropertyChanged("ISS_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public System.Nullable<System.DateTime> RQC_DATE {
            get {
                return this.RQC_DATEField;
            }
            set {
                if ((this.RQC_DATEField.Equals(value) != true)) {
                    this.RQC_DATEField = value;
                    this.RaisePropertyChanged("RQC_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string UPD_USER {
            get {
                return this.UPD_USERField;
            }
            set {
                if ((object.ReferenceEquals(this.UPD_USERField, value) != true)) {
                    this.UPD_USERField = value;
                    this.RaisePropertyChanged("UPD_USER");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=20)]
        public System.Nullable<System.DateTime> UPD_DATE {
            get {
                return this.UPD_DATEField;
            }
            set {
                if ((this.UPD_DATEField.Equals(value) != true)) {
                    this.UPD_DATEField = value;
                    this.RaisePropertyChanged("UPD_DATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string WH_LOC {
            get {
                return this.WH_LOCField;
            }
            set {
                if ((object.ReferenceEquals(this.WH_LOCField, value) != true)) {
                    this.WH_LOCField = value;
                    this.RaisePropertyChanged("WH_LOC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string VEN_LTNO {
            get {
                return this.VEN_LTNOField;
            }
            set {
                if ((object.ReferenceEquals(this.VEN_LTNOField, value) != true)) {
                    this.VEN_LTNOField = value;
                    this.RaisePropertyChanged("VEN_LTNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.Nullable<System.DateTime> MAKE_DATE {
            get {
                return this.MAKE_DATEField;
            }
            set {
                if ((this.MAKE_DATEField.Equals(value) != true)) {
                    this.MAKE_DATEField = value;
                    this.RaisePropertyChanged("MAKE_DATE");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="USAPReference.USAPWebServiceSoap")]
    public interface USAPWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name BC_NO from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByBcNo", ReplyAction="*")]
        Line_Production.USAPReference.GetByBcNoResponse GetByBcNo(Line_Production.USAPReference.GetByBcNoRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProduct", ReplyAction="*")]
        Line_Production.USAPReference.GetActualProductResponse GetActualProduct(Line_Production.USAPReference.GetActualProductRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetActualProductWidthKey", ReplyAction="*")]
        Line_Production.USAPReference.GetActualProductWidthKeyResponse GetActualProductWidthKey(Line_Production.USAPReference.GetActualProductWidthKeyRequest request);
        
        // CODEGEN: Generating message contract since element name issue from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetByIssueSheet", ReplyAction="*")]
        Line_Production.USAPReference.GetByIssueSheetResponse GetByIssueSheet(Line_Production.USAPReference.GetByIssueSheetRequest request);
        
        // CODEGEN: Generating message contract since element name GetListReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListReport", ReplyAction="*")]
        Line_Production.USAPReference.GetListReportResponse GetListReport(Line_Production.USAPReference.GetListReportRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataPointsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPoints", ReplyAction="*")]
        Line_Production.USAPReference.GetDataPointsResponse GetDataPoints(Line_Production.USAPReference.GetDataPointsRequest request);
        
        // CODEGEN: Generating message contract since element name GetDataPointConfirmsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataPointConfirms", ReplyAction="*")]
        Line_Production.USAPReference.GetDataPointConfirmsResponse GetDataPointConfirms(Line_Production.USAPReference.GetDataPointConfirmsRequest request);
        
        // CODEGEN: Generating message contract since element name DailyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Daily", ReplyAction="*")]
        Line_Production.USAPReference.DailyResponse Daily(Line_Production.USAPReference.DailyRequest request);
        
        // CODEGEN: Generating message contract since element name MonthlyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Monthly", ReplyAction="*")]
        Line_Production.USAPReference.MonthlyResponse Monthly(Line_Production.USAPReference.MonthlyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByBcNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByBcNo", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetByBcNoRequestBody Body;
        
        public GetByBcNoRequest() {
        }
        
        public GetByBcNoRequest(Line_Production.USAPReference.GetByBcNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByBcNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BC_NO;
        
        public GetByBcNoRequestBody() {
        }
        
        public GetByBcNoRequestBody(string BC_NO) {
            this.BC_NO = BC_NO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByBcNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByBcNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetByBcNoResponseBody Body;
        
        public GetByBcNoResponse() {
        }
        
        public GetByBcNoResponse(Line_Production.USAPReference.GetByBcNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByBcNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Line_Production.USAPReference.BCLBFLMEntity GetByBcNoResult;
        
        public GetByBcNoResponseBody() {
        }
        
        public GetByBcNoResponseBody(Line_Production.USAPReference.BCLBFLMEntity GetByBcNoResult) {
            this.GetByBcNoResult = GetByBcNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProduct", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetActualProductRequestBody Body;
        
        public GetActualProductRequest() {
        }
        
        public GetActualProductRequest(Line_Production.USAPReference.GetActualProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endTime;
        
        public GetActualProductRequestBody() {
        }
        
        public GetActualProductRequestBody(string user, System.DateTime startTime, System.DateTime endTime) {
            this.user = user;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetActualProductResponseBody Body;
        
        public GetActualProductResponse() {
        }
        
        public GetActualProductResponse(Line_Production.USAPReference.GetActualProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActualProductResult;
        
        public GetActualProductResponseBody() {
        }
        
        public GetActualProductResponseBody(string GetActualProductResult) {
            this.GetActualProductResult = GetActualProductResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductWidthKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductWidthKey", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetActualProductWidthKeyRequestBody Body;
        
        public GetActualProductWidthKeyRequest() {
        }
        
        public GetActualProductWidthKeyRequest(Line_Production.USAPReference.GetActualProductWidthKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductWidthKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endTime;
        
        public GetActualProductWidthKeyRequestBody() {
        }
        
        public GetActualProductWidthKeyRequestBody(string user, string key, System.DateTime startTime, System.DateTime endTime) {
            this.user = user;
            this.key = key;
            this.startTime = startTime;
            this.endTime = endTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetActualProductWidthKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetActualProductWidthKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetActualProductWidthKeyResponseBody Body;
        
        public GetActualProductWidthKeyResponse() {
        }
        
        public GetActualProductWidthKeyResponse(Line_Production.USAPReference.GetActualProductWidthKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetActualProductWidthKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetActualProductWidthKeyResult;
        
        public GetActualProductWidthKeyResponseBody() {
        }
        
        public GetActualProductWidthKeyResponseBody(string GetActualProductWidthKeyResult) {
            this.GetActualProductWidthKeyResult = GetActualProductWidthKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIssueSheetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIssueSheet", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetByIssueSheetRequestBody Body;
        
        public GetByIssueSheetRequest() {
        }
        
        public GetByIssueSheetRequest(Line_Production.USAPReference.GetByIssueSheetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIssueSheetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string issue;
        
        public GetByIssueSheetRequestBody() {
        }
        
        public GetByIssueSheetRequestBody(string issue) {
            this.issue = issue;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIssueSheetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIssueSheetResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetByIssueSheetResponseBody Body;
        
        public GetByIssueSheetResponse() {
        }
        
        public GetByIssueSheetResponse(Line_Production.USAPReference.GetByIssueSheetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIssueSheetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetByIssueSheetResult;
        
        public GetByIssueSheetResponseBody() {
        }
        
        public GetByIssueSheetResponseBody(string GetByIssueSheetResult) {
            this.GetByIssueSheetResult = GetByIssueSheetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListReport", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetListReportRequestBody Body;
        
        public GetListReportRequest() {
        }
        
        public GetListReportRequest(Line_Production.USAPReference.GetListReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetListReportRequestBody {
        
        public GetListReportRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetListReportResponseBody Body;
        
        public GetListReportResponse() {
        }
        
        public GetListReportResponse(Line_Production.USAPReference.GetListReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetListReportResult;
        
        public GetListReportResponseBody() {
        }
        
        public GetListReportResponseBody(string GetListReportResult) {
            this.GetListReportResult = GetListReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPoints", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetDataPointsRequestBody Body;
        
        public GetDataPointsRequest() {
        }
        
        public GetDataPointsRequest(Line_Production.USAPReference.GetDataPointsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataPointsRequestBody {
        
        public GetDataPointsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetDataPointsResponseBody Body;
        
        public GetDataPointsResponse() {
        }
        
        public GetDataPointsResponse(Line_Production.USAPReference.GetDataPointsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPointsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataPointsResult;
        
        public GetDataPointsResponseBody() {
        }
        
        public GetDataPointsResponseBody(string GetDataPointsResult) {
            this.GetDataPointsResult = GetDataPointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointConfirmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointConfirms", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetDataPointConfirmsRequestBody Body;
        
        public GetDataPointConfirmsRequest() {
        }
        
        public GetDataPointConfirmsRequest(Line_Production.USAPReference.GetDataPointConfirmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataPointConfirmsRequestBody {
        
        public GetDataPointConfirmsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataPointConfirmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataPointConfirmsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.GetDataPointConfirmsResponseBody Body;
        
        public GetDataPointConfirmsResponse() {
        }
        
        public GetDataPointConfirmsResponse(Line_Production.USAPReference.GetDataPointConfirmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataPointConfirmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDataPointConfirmsResult;
        
        public GetDataPointConfirmsResponseBody() {
        }
        
        public GetDataPointConfirmsResponseBody(string GetDataPointConfirmsResult) {
            this.GetDataPointConfirmsResult = GetDataPointConfirmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Daily", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.DailyRequestBody Body;
        
        public DailyRequest() {
        }
        
        public DailyRequest(Line_Production.USAPReference.DailyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime input;
        
        public DailyRequestBody() {
        }
        
        public DailyRequestBody(System.DateTime input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DailyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DailyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.DailyResponseBody Body;
        
        public DailyResponse() {
        }
        
        public DailyResponse(Line_Production.USAPReference.DailyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DailyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DailyResult;
        
        public DailyResponseBody() {
        }
        
        public DailyResponseBody(string DailyResult) {
            this.DailyResult = DailyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthlyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Monthly", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.MonthlyRequestBody Body;
        
        public MonthlyRequest() {
        }
        
        public MonthlyRequest(Line_Production.USAPReference.MonthlyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MonthlyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime input;
        
        public MonthlyRequestBody() {
        }
        
        public MonthlyRequestBody(System.DateTime input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MonthlyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MonthlyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Line_Production.USAPReference.MonthlyResponseBody Body;
        
        public MonthlyResponse() {
        }
        
        public MonthlyResponse(Line_Production.USAPReference.MonthlyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MonthlyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MonthlyResult;
        
        public MonthlyResponseBody() {
        }
        
        public MonthlyResponseBody(string MonthlyResult) {
            this.MonthlyResult = MonthlyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface USAPWebServiceSoapChannel : Line_Production.USAPReference.USAPWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class USAPWebServiceSoapClient : System.ServiceModel.ClientBase<Line_Production.USAPReference.USAPWebServiceSoap>, Line_Production.USAPReference.USAPWebServiceSoap {
        
        public USAPWebServiceSoapClient() {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USAPWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public USAPWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetByBcNoResponse Line_Production.USAPReference.USAPWebServiceSoap.GetByBcNo(Line_Production.USAPReference.GetByBcNoRequest request) {
            return base.Channel.GetByBcNo(request);
        }
        
        public Line_Production.USAPReference.BCLBFLMEntity GetByBcNo(string BC_NO) {
            Line_Production.USAPReference.GetByBcNoRequest inValue = new Line_Production.USAPReference.GetByBcNoRequest();
            inValue.Body = new Line_Production.USAPReference.GetByBcNoRequestBody();
            inValue.Body.BC_NO = BC_NO;
            Line_Production.USAPReference.GetByBcNoResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetByBcNo(inValue);
            return retVal.Body.GetByBcNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetActualProductResponse Line_Production.USAPReference.USAPWebServiceSoap.GetActualProduct(Line_Production.USAPReference.GetActualProductRequest request) {
            return base.Channel.GetActualProduct(request);
        }
        
        public string GetActualProduct(string user, System.DateTime startTime, System.DateTime endTime) {
            Line_Production.USAPReference.GetActualProductRequest inValue = new Line_Production.USAPReference.GetActualProductRequest();
            inValue.Body = new Line_Production.USAPReference.GetActualProductRequestBody();
            inValue.Body.user = user;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            Line_Production.USAPReference.GetActualProductResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetActualProduct(inValue);
            return retVal.Body.GetActualProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetActualProductWidthKeyResponse Line_Production.USAPReference.USAPWebServiceSoap.GetActualProductWidthKey(Line_Production.USAPReference.GetActualProductWidthKeyRequest request) {
            return base.Channel.GetActualProductWidthKey(request);
        }
        
        public string GetActualProductWidthKey(string user, string key, System.DateTime startTime, System.DateTime endTime) {
            Line_Production.USAPReference.GetActualProductWidthKeyRequest inValue = new Line_Production.USAPReference.GetActualProductWidthKeyRequest();
            inValue.Body = new Line_Production.USAPReference.GetActualProductWidthKeyRequestBody();
            inValue.Body.user = user;
            inValue.Body.key = key;
            inValue.Body.startTime = startTime;
            inValue.Body.endTime = endTime;
            Line_Production.USAPReference.GetActualProductWidthKeyResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetActualProductWidthKey(inValue);
            return retVal.Body.GetActualProductWidthKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetByIssueSheetResponse Line_Production.USAPReference.USAPWebServiceSoap.GetByIssueSheet(Line_Production.USAPReference.GetByIssueSheetRequest request) {
            return base.Channel.GetByIssueSheet(request);
        }
        
        public string GetByIssueSheet(string issue) {
            Line_Production.USAPReference.GetByIssueSheetRequest inValue = new Line_Production.USAPReference.GetByIssueSheetRequest();
            inValue.Body = new Line_Production.USAPReference.GetByIssueSheetRequestBody();
            inValue.Body.issue = issue;
            Line_Production.USAPReference.GetByIssueSheetResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetByIssueSheet(inValue);
            return retVal.Body.GetByIssueSheetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetListReportResponse Line_Production.USAPReference.USAPWebServiceSoap.GetListReport(Line_Production.USAPReference.GetListReportRequest request) {
            return base.Channel.GetListReport(request);
        }
        
        public string GetListReport() {
            Line_Production.USAPReference.GetListReportRequest inValue = new Line_Production.USAPReference.GetListReportRequest();
            inValue.Body = new Line_Production.USAPReference.GetListReportRequestBody();
            Line_Production.USAPReference.GetListReportResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetListReport(inValue);
            return retVal.Body.GetListReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetDataPointsResponse Line_Production.USAPReference.USAPWebServiceSoap.GetDataPoints(Line_Production.USAPReference.GetDataPointsRequest request) {
            return base.Channel.GetDataPoints(request);
        }
        
        public string GetDataPoints() {
            Line_Production.USAPReference.GetDataPointsRequest inValue = new Line_Production.USAPReference.GetDataPointsRequest();
            inValue.Body = new Line_Production.USAPReference.GetDataPointsRequestBody();
            Line_Production.USAPReference.GetDataPointsResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetDataPoints(inValue);
            return retVal.Body.GetDataPointsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.GetDataPointConfirmsResponse Line_Production.USAPReference.USAPWebServiceSoap.GetDataPointConfirms(Line_Production.USAPReference.GetDataPointConfirmsRequest request) {
            return base.Channel.GetDataPointConfirms(request);
        }
        
        public string GetDataPointConfirms() {
            Line_Production.USAPReference.GetDataPointConfirmsRequest inValue = new Line_Production.USAPReference.GetDataPointConfirmsRequest();
            inValue.Body = new Line_Production.USAPReference.GetDataPointConfirmsRequestBody();
            Line_Production.USAPReference.GetDataPointConfirmsResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).GetDataPointConfirms(inValue);
            return retVal.Body.GetDataPointConfirmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.DailyResponse Line_Production.USAPReference.USAPWebServiceSoap.Daily(Line_Production.USAPReference.DailyRequest request) {
            return base.Channel.Daily(request);
        }
        
        public string Daily(System.DateTime input) {
            Line_Production.USAPReference.DailyRequest inValue = new Line_Production.USAPReference.DailyRequest();
            inValue.Body = new Line_Production.USAPReference.DailyRequestBody();
            inValue.Body.input = input;
            Line_Production.USAPReference.DailyResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).Daily(inValue);
            return retVal.Body.DailyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Line_Production.USAPReference.MonthlyResponse Line_Production.USAPReference.USAPWebServiceSoap.Monthly(Line_Production.USAPReference.MonthlyRequest request) {
            return base.Channel.Monthly(request);
        }
        
        public string Monthly(System.DateTime input) {
            Line_Production.USAPReference.MonthlyRequest inValue = new Line_Production.USAPReference.MonthlyRequest();
            inValue.Body = new Line_Production.USAPReference.MonthlyRequestBody();
            inValue.Body.input = input;
            Line_Production.USAPReference.MonthlyResponse retVal = ((Line_Production.USAPReference.USAPWebServiceSoap)(this)).Monthly(inValue);
            return retVal.Body.MonthlyResult;
        }
    }
}
